---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: {DOMAIN}
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: '{IP}'
            forwarded_port: {  }
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_hl2aovg7ee57:
                owner: www-data
                group: www-data
                source: ./.modman
                target: /home/vagrant/.modman
                sync_type: rsync
                rsync:
                    args:
                        - '-avzO'
                        - '--delete'
                        - '--chmod=Dug=rwx,o=rx,Fug=rw,o=r'
                    exclude:
                        - .git/
                        - /src
                    auto: 'true'
            vflsf_ngiqigfg57tj:
                owner: www-data
                group: www-data
                source: ./vendor
                target: /home/vagrant/vendor
                sync_type: rsync
                rsync:
                    args:
                        - '-avzO'
                        - '--delete'
                        - '--chmod=Dug=rwx,o=rx,Fug=rw,o=r'
                    exclude:
                        - .git/
                    auto: 'true'
            vflsf_5f6uz9e1r73h:
                owner: www-data
                group: www-data
                source: ./src
                target: /home/vagrant/src
                sync_type: rsync
                rsync:
                    args:
                        - '-avzO'
                        - '--delete'
                        - '--chmod=Dug=rwx,o=rx,Fug=rw,o=r'
                    exclude:
                        - .git/
                    auto: 'true'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - libnss-mdns
        - curl
        - git
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs:
        cj_yr02kxqn3eeo:
            name: 'Magento Cronjob (Default)'
            user: vagrant
            command: 'php /var/www/{DOMAIN}/cron.php -mdefault'
            minute: '*/1'
            hour: '*'
            weekday: '*'
            month: '*'
            monthday: ''
        cj_e12hvtjusj15:
            name: 'Magento Cronjob (Always)'
            user: vagrant
            command: 'php /var/www/{DOMAIN}/cron.php -malways'
            minute: '*/1'
            hour: '*'
            weekday: '*'
            month: '*'
            monthday: ''
firewall:
    install: '1'
    rules: {  }
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_b43g7mdeyfsh:
            servername: '{DOMAIN}'
            serveraliases:
                - 'www.{DOMAIN}'
            docroot: '/var/www/{DOMAIN}'
            port: '80'
            setenv:
                - 'MAGE_IS_DEVELOPER_MODE 1'
            custom_fragment: ''
            directories:
                avd_fqwlfk8hr7fm:
                    provider: directory
                    path: /var/www/{DOMAIN}
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_kfby6r85sg3u:
                            provider: filesmatch
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
nginx:
    install: '1'
    settings:
        default_vhost: 0
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        client_body_buffer_size: 2222m
    upstreams: {  }
    proxies: {  }
    vhosts:
        nxv_magento:
            server_name: '{DOMAIN}'
            www_root: '/var/www/{DOMAIN}'
            use_default_location: false
            listen_port: '80'
            index_files:
                - index.html
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '0'
            spdy: '0'
            locations:
                nxvl_root:
                    location: /
                    autoindex: 'off'
                    try_files:
                        - $uri
                        - $uri/
                        - '@handler'
                nxvl_skin:
                    location: /skin/
                    try_files:
                        - $uri
                        - '=404'
                    raw_prepend: 'expires 5d; access_log off;'
                    index_files: []
                nxvl_media:
                    location: /media/
                    try_files:
                        - $uri
                        - '=404'
                    raw_prepend: 'expires 6d; access_log off;'
                    index_files: []
                nxvl_js:
                    location: /js/
                    raw_prepend: 'expires 7d; access_log off;'
                    try_files:
                        - $uri
                        - '=404'
                    index_files: []
                nxvl_varexport:
                    location: /var/export/
                    internal: true
                    index_files: []
                nxvl_404:
                    location: /.
                    index_files: []
                    raw_append: 'return 404;'
                nxvl_handler:
                    location: '@handler'
                    raw_append: 'rewrite / /index.php;'
                    index_files: []
                nxvl_foobar:
                    location: '~* \.php/'
                    location_cfg_append:
                        rewrite: ^(.*.php)/ $1 last
                nxvl_y62hol82cfm6:
                    location: '~* \.php$'
                    raw_prepend: |
                        if (!-e $request_filename) { rewrite / /index.php last; }
                        expires off;
                    autoindex: 'off'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                        - 'MAGE_IS_DEVELOPER_MODE 1'
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - gd
            - curl
            - mysql
            - tidy
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        memory_limit: '256M'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_un7wssf40hsd:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    fpm_settings:
        port: 9000
    composer: '1'
    composer_home: ''
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '0'
        xdebug.remote_host: 10.0.2.2
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.idekey: xdebug
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: ''
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: root
        override_options: {  }
    adminer: 0
    users:
        kXV7WQiYMVxx:
            name: magento
            password: root
    databases:
        IUU7JNcL2zkA:
            name: magento
            sql: ''
    grants:
        xljJ9PyTkUvi:
            user: magento
            table: magento.*
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: ''
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '1'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: headers
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: ''
        port: ''

