---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: '{DOMAIN}'
        memory: '1024'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: '{IP}'
            forwarded_port: {  }
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            DPLgudwyiTRs:
                owner: www-data
                group: www-data
                source: '{SOURCE_DIR}'
                target: /home/vagrant/www
                sync_type: rsync
                rsync:
                    args:
                        - '-avzO'
                        - '--delete'
                        - '--chmod=Dug=rwx,o=rx,Fug=rw,o=r'
                    exclude:
                        - .git/
                        - /media/
                        - /var/
                        - app/etc/local.xml
                    auto: 'true'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - libnss-mdns
        - curl
        - git
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs:
        syw5tits7oed:
            monthday: ''
            name: 'Magento Cronjob (Default)'
            user: vagrant
            command: 'php /var/www/{DOMAIN}/cron.php -mdefault'
            minute: '*/1'
            hour: '*'
            weekday: '*'
            month: '*'
        ixrk2utvdrnr:
            monthday: ''
            name: 'Magento Cronjob (Always)'
            user: vagrant
            command: 'php /var/www/{DOMAIN}/cron.php -malways'
            minute: '*/1'
            hour: '*'
            weekday: '*'
            month: '*'
firewall:
    install: '1'
    rules: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - deflate
        - expires
        - headers
        - info
        - proxy
        - rewrite
    vhosts:
        u57lkdl8n6hf:
            servername: '{DOMAIN}'
            serveraliases:
                - 'www.{DOMAIN}'
            docroot: '/var/www/{DOMAIN}'
            port: '80'
            setenv:
                - 'MAGE_IS_DEVELOPER_MODE 1'
            custom_fragment: ''
            directories:
                dynausnskjm4:
                    provider: directory
                    path: /var/www/{DOMAIN}
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all granted
                    custom_fragment: ''
                    files_match:
                        gqbzshteei60:
                            provider: filesmatch
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        gff3fxpmfkpu:
            servername: '{DOMAIN}'
            serveraliases:
                - 'www.{DOMAIN}'
            docroot: '/var/www/{DOMAIN}'
            port: '443'
            setenv:
                - 'MAGE_IS_DEVELOPER_MODE 1'
            custom_fragment: ''
            directories:
                dynausnskjm4:
                    provider: directory
                    path: /var/www/{DOMAIN}
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all granted
                    custom_fragment: ''
                    files_match:
                        gqbzshteei60:
                            provider: filesmatch
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts: {  }
php:
    install: '1'
    settings:
        version: '54'
    fpm_settings:
        port: 9000
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - gd
            - curl
            - mysql
            - tidy
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '0'
        xdebug.remote_host: 10.0.2.2
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.idekey: xdebug
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: ''
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        A0mz1N3Ben21:
            version: ''
nodejs:
    install: '0'
    npm_packages:
        - grunt-cli
        - bower
python:
    install: '1'
    packages: {  }
    versions:
        BIox1tnac55S:
            version: ''
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: 'root'
        override_options: {  }
    adminer: 0
    users:
        kXV7WQiYMVxx:
            name: magento
            password: root
    databases:
        HEstDEIlxUxt:
            name: magento
            sql: ''
    grants:
        xljJ9PyTkUvi:
            user: magento
            table: magento.*
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: ''
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '1'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: headers
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: null
        java_install: true
solr:
    install: '0'
    settings:
        version: ''
        port: ''

